### ISSUE TITLE
Update Contributing Checklist

### ISSUE THREAD

**Issue by NiklasMerz** [apache/cordova-contribute#36]
As discussed on list and in #35 this is the list of updated repos. **NEW** means CONTRIBUTING.md did not exist before. All active repos from https://github.com/apache/cordova

- [x]     apache/cordova-android
- [x]     apache/cordova-ios
- [x]     apache/cordova-windows
- [x]     apache/cordova-browser
- [x]     apache/cordova-osx
- [x]     apache/cordova-test-platform
- [x]     apache/cordova-electron
- [x]     apache/cordova-plugin-battery-status
- [x]     apache/cordova-plugin-camera
- [x]     apache/cordova-plugin-device
- [x]     apache/cordova-plugin-dialogs
- [x]     apache/cordova-plugin-file
- [x]     apache/cordova-plugin-geolocation
- [x]     apache/cordova-plugin-inappbrowser
- [x]     apache/cordova-plugin-media
- [x]     apache/cordova-plugin-media-capture
- [x]     apache/cordova-plugin-network-information
- [x]     apache/cordova-plugin-screen-orientation **NEW**
- [x]     apache/cordova-plugin-splashscreen
- [x]     apache/cordova-plugin-statusbar
- [x]     apache/cordova-plugin-vibration
- [x]     apache/cordova-plugin-whitelist
- [x]     apache/cordova-plugin-wkwebview-engine
- [x]     apache/cordova-cli
- [x]     apache/cordova-plugman
- [x]     apache/cordova-coho
- [x]     apache/cordova-js
- [x]     apache/cordova-lib
- [x]     apache/cordova-common **NEW**
- [x]     apache/cordova-create **NEW**
- [x]     apache/cordova-fetch **NEW**
- [x]     apache/cordova-serve **NEW**
- [x]     apache/cordova-plugin-test-framework **NEW**
- [x]     apache/cordova-paramedic **NEW**
- [x]     apache/cordova-mobile-spec
- [x]     apache/cordova-app-hello-world
- [x]     apache/cordova
- [x]     apache/cordova-docs
- [x]    apache/cordova-node-xcode

**Comment by NiklasMerz** [comment]
Update done. I used this script and committed directly to master:

```
git checkout master
git pull origin master
cp ../CONTRIBUTING.md CONTRIBUTING.md
git add CONTRIBUTING.md
git commit -m "Update CONTRIBUTING.md"
git log --name-status HEAD^..HEAD
git diff HEAD^ HEAD
git remote add ssh git@github.com:apache/${PWD##*/}.git
```

Used with `apache` directory like coho.
